Assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Project/', include('MyApp.urls', namespace='MyApp')),
]

MyApp/urls.py
from django.urls import path
from . import views
app_name = 'MyApp'

urlpatterns = [
    path('signin/',views.sign_up,name='signup'),
    path('login/',views.userLogin,name='login'),
    path('logout/',views.userLogout,name='logout'),
    path('',views.projectHome,name='home'),
    path('edit/<int:pk>/',views.editProject,name='edit'),
    path('details/<int:pk>/',views.viewProject,name='details'),
    path('delete/<int:pk>/',views.deleteProject, name='delete'),
]

MyApp/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.utils import timezone 
class User(AbstractUser):
    is_manager=models.BooleanField(default=False)
    is_viewer=models.BooleanField(default=True)

class Project(models.Model):
    name = models.CharField(max_length=20, null=False)
    start = models.DateField()
    end = models.DateField()
    value = models.DecimalField(max_digits=50, decimal_places=5)

class DeletedProjects(models.Model):
    name = models.CharField(max_length=20, null=False)
    start = models.DateField()
    end = models.DateField()
    value = models.DecimalField(max_digits=50, decimal_places=5)
    deleted=models.DateTimeField(auto_now_add=timezone.now())

MyApp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Layout, Submit, Row, Column

class SignInForm(forms.Form):
    username=forms.CharField(label='Username')
    email=forms.EmailField(label='Email',widget=forms.EmailInput)
    password=forms.CharField(widget=forms.PasswordInput,label='Password')
    password_re=forms.CharField(widget=forms.PasswordInput,label='Re-Enter Password')
    is_manager=forms.BooleanField(label='Manager',required=False)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_action = ''
        self.helper.layout = Layout(
            Row(
                Column('username',css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('email',css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password', css_class='form-group col-md-6 mb-0'),
                Column('password_re', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'is_manager',
            Submit('submit', 'Create', css_class='btn btn-primary')
        )
    def clean(self):
        cleaned_data = super(SignInForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("password_re")

        if password != confirm_password:
            raise forms.ValidationError(
                "Passwords does not match"
            )


class LogInForm(forms.Form):
    username=forms.CharField(label='Username')
    password=forms.CharField(widget=forms.PasswordInput,label='Password')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_action = ''
        self.helper.layout = Layout(
            Row(
                Column('username',css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Login', css_class='btn btn-primary')
        )


class ProjectForm(forms.Form):
    name=forms.CharField(label='Name')
    start=forms.DateField(label='Start',widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    end=forms.DateField(label='End',widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    value=forms.DecimalField(label='Value (in Doller)')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_action = ''
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('start', css_class='form-group col-md-4 mb-0'),
                Column('end', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('value',css_class='form-group col-md-6 mb-0'),
            ),
            Submit('pro_submit', 'Create Project', css_class='btn btn-success')
        )

MyApp/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import ProjectForm,LogInForm,SignInForm
from .models import Project,User,DeletedProjects
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login,logout
from django.forms.models import model_to_dict
from .decorators import is_u_manager
from django.contrib import messages

@login_required
def projectHome(request):
    if request.method == 'POST':
        form=ProjectForm()
        if 'pro_submit' in request.POST:
            form = ProjectForm(request.POST)
            if form.is_valid():
                project=Project()
                project.name=form.cleaned_data['name']
                project.start=form.cleaned_data['start']
                project.end=form.cleaned_data['end']
                project.value=form.cleaned_data['value']
                project.save()
                return HttpResponseRedirect(reverse('MyApp:home'))
    else:
        form = ProjectForm()

    projects=Project.objects.all()
    deleted=DeletedProjects.objects.all()
    #Securing delted data to all viewers 
    if request.user.is_manager:
        context = {'form': form,'projects':projects,'deleted':deleted}
    else:
        context={'form': form,'projects':projects}
    return render(request,'MyApp/home.html',context)

@login_required
@is_u_manager
def editProject(request,pk):
    instance=get_object_or_404(Project, id=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project=Project.objects.get()
            project.name=form.cleaned_data['name']
            project.start=form.cleaned_data['start']
            project.end=form.cleaned_data['end']
            project.value=form.cleaned_data['value']
            project.save()
            return HttpResponseRedirect(reverse('MyApp:home'))
    else:
        form = ProjectForm(initial=model_to_dict(instance))
    context = {'form': form}
    return render(request,'MyApp/edit.html',context)

@login_required
def viewProject(request,pk):
    instance=get_object_or_404(Project, id=pk)
    form = ProjectForm(initial=model_to_dict(instance))
    context = {'form': form}
    return render(request,'MyApp/details.html',context)


def userLogin(request):
    if request.method=='POST':
        form=LogInForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('MyApp:home'))
            else:
                messages.error(request,'Username or Password not correct')
                return HttpResponseRedirect(reverse('MyApp:login'))
    else:
        form=LogInForm()
    context={'form':form}
    return render(request,'MyApp/login.html',context)

def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('MyApp:login'))

def sign_up(request):
    if request.method=='POST':
        form=SignInForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if User.objects.filter(username=cd['username']).exists():
                messages.error(request,'Username Already Exists')
                return HttpResponseRedirect(reverse('MyApp:signup'))
                
            else:
                user=User()
                user.username=cd['username']
                user.set_password(cd['password'])
                user.is_manager=cd['is_manager']
                user.save()
                return HttpResponseRedirect(reverse('MyApp:login'))
    else:
        form=SignInForm()
    context={'form':form}
    return render(request,'MyApp/signup.html',context)

@login_required
@is_u_manager
def deleteProject(request,pk):
    project=Project.objects.get(id=pk)
    deletedpro=DeletedProjects.objects.create(name=project.name,start=project.start,end=project.end,value=project.value)
    deletedpro.save()
    project.delete()
    return HttpResponse('')

MyApp/templates/MyApp/details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Project Details{% endblock %}
{% block content %}
{{form.name|as_crispy_field }}
{{ form.start|as_crispy_field }}
{{ form.end|as_crispy_field }}
{{ form.value|as_crispy_field }}
{% endblock %}

MyApp/templates/MyApp/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit Project{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-row form-row">
        <div class="form-group col-md-6 mb-0">
            {{form.name|as_crispy_field }}
        </div>
    </div>
    <div class="form-row form-row">
        <div class="form-group col-md-6 mb-0">
            {{ form.start|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.end|as_crispy_field }}
        </div>
    </div>
    <div class="form-row form-row">
        <div class="form-group col-md-6 mb-0">
            {{ form.value|as_crispy_field }}
        </div>
    </div>
    <input type="submit" value="Update" class="btn btn-primary">
</form>
{% endblock %}

MyApp/templates/MyApp/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Welcome to Project Management{% endblock %}
{% block content %}
<div class="card-columns">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Project</h4>
            <button class="btn btn-primary btn-lg" type="button"  data-toggle="modal" data-target="#createpro">Create</button>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">List All Projects</h4>
            <button class="btn btn-info btn-lg" type="button" data-toggle="modal" data-target="#listpro">View</button>
        </div>
    </div>
    {% if request.user.is_manager %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deleted Projects</h4>
            <button class="btn btn-primary btn-lg" type="button"  data-toggle="modal" data-target="#deletedpro">Show</button>
        </div>
    </div>
    {% endif %}
</div>
<!-- List All Project -->
<div class="modal fade" id="listpro" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">All Projects</h1>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    {% for project in projects %}
                        <li class="list-group-item d-flex justify-content-between align-items-center" id="project_{{project.id}}">
                            <a href="{% url 'MyApp:details' project.id %}"> {{project.name }}</a>
                            {% if request.user.is_manager %}
                            <div class="row">
                            <span class="badge badge-info">
                                <a href="{% url 'MyApp:edit' project.id %}"><button type="button" class="btn btn-info">Edit</button></a>
                            </span>
                            <span class="badge badge-warning" style="margin-left: 5px;">
                                <button class="btn btn-warning btn-sm" onclick="submit_delete({{ project.id }})" >Delete</button>
                            </span>
                            </div>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- Create New Project -->
<div class="modal fade" id="createpro" data-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Create Projects</h1>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                {% crispy form %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- Deleted Project -->
<div class="modal fade" id="deletedpro" data-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">All Deleted Projects</h1>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    {% for del in deleted %}
                    <li class="list-group-item d-flex justify-content-between align-items-center" id="deleted-items">
                        <h5>{{ del.name }}</h3>
                        <h8>{{ del.deleted }}</h5>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MyApp/templates/MyApp/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block content %}
{% for message in messages %}
<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
</div>
{% endfor %}
{% crispy form %}
{{form.errors}}
<div style="margin-top: 5%;">
    <h5>Don't have a Account <a href="{% url "MyApp:signup" %}"><span class="badge badge-success">Create</span></a>
    </h5>
</div>
{% endblock %}

MyApp/templates/MyApp/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Signin{% endblock %}
{% block content %}
{% for message in messages %}
<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
</div>
{% endfor %}
{% crispy form %}
{% endblock %}